language: python
python:
  - "3.7"
# command to install dependencies
env:
  - SECRET_KEY='0n6$t9bxv1vm(p(z&rjc7$lmpl3)t&q2t(7qhpkec(tt(_&znr'
services: 
  - postgresql
install: 
  - pipenv install
# command to run tests
script:
  - python manage.py test