language: python
python:
  - "3.7"
# command to install dependencies
env:
  - DJANGO_VERSION=2.2.6
services: 
  - postgresql
install: 
  - pipenv install
# command to run tests
script:
  - python3 manage.py migrate
  - python3 manage.py test