# Generated by Django 3.1.1 on 2020-10-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user_choice',
            new_name='choice',
        ),
    ]
